### ISSUE TITLE
Broken Demo!

### ISSUE THREAD

**Issue by onrea** [digitalcraftsman/hugo-read-the-docs#9]
http://themes.gohugo.io/material-docs --> The demo link is broken!

**Comment by digitalcraftsman** [comment]
Hello @onrea,

I know that the current demo of the [Material Docs](https://github.com/digitalcraftsman/hugo-material-docs) theme is broken. The stylesheets aren't loaded [completely](http://themes.gohugo.io/theme/material-docs/stylesheets/palettes.css) - the end is always chomped. I'm searching for the source of this odd behavior but wasn't successful so far. 

However, for this reason I hosted a [demo](https://digitalcraftsman.github.io/hugo-material-docs/) myself. The theme itself is not broken and can be used without any issues like in the demo.

PS: This repository doesn't contain the source code for this theme. Look [here](https://github.com/digitalcraftsman/hugo-material-docs) :wink:
